### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by LLLYLong** [serdarch/SERNet-Former#1]
Thanks to the author for such a great job, I would like to ask, about what time will the source code of the article be provided?

**Comment by serdarch** [comment]
Many thanks for your question and interests.
The network is still being used to be developed and may be subjected to
national property rights for the time being.
Thus, the source code of the network is planned to be released later.

25 Mar 2024 Pzt 04:49 tarihinde LLLYLong ***@***.***> şunu
yazdı:
