### ISSUE TITLE
...___...

### ISSUE THREAD

**Issue by takaniwa** [serdarch/SERNet-Former#10]
Show me the real code, weights, and network details; otherwise, don't boast. ... From the overall structure, I can't imagine that this model's performance can surpass excellent network InternImage...

**Comment by serdarch** [comment]
It is very nice to be compared with OpenGVLab's project InternImage! 
Indeed, there are many other projects/repositories that announce their results better than these projects. 
So, I really could not get your point?!

On the other hand, we could be more kind and respectful to each other in this very defined community!

Let me briefly explain that SERNet-Former is a project that has academic, legal, and financial aspects and it becomes impossible to share its code directly.
Moreover, its decoder part is developed with CNN and attention-based transformer layers. So, it is pretty normal to perform as competitive as Mask2Former architectures.
And, it is unfortunate for you that, indeed, all results are real as you may check some of them on public websites!
