### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by shaoyandea** [serdarch/SERNet-Former#3]
your work is great! can you release code , i am very interesting in it

**Comment by serdarch** [comment]
Many thanks for your comments and interests.
I have just committed some updates to the codes and added new examplar codes.
Please find them in the repo.

Please also ensure that the original model is being developed in MATLAB. 
Thus, the code is fundamentally different from PyTorch.
So, this repository is only being developed for additional language support and as a backup repository to the network 
with many basic and tutorial-based codes to emulate the development progress of the network.

I hope this answers your inquiry.
Best

**Comment by serdarch** [comment]
This repository is only being developed for additional language support and as a backup repository to the network
with many basic and tutorial-based codes to emulate the development progress of the network.

I hope this answers your inquiry.
Best

**Comment by shaoyandea** [comment]
thank you for your reply,&nbsp; I am doing some research about semantic segmentation and I believe this code and paper will give me great help in research, hoping for&nbsp; complete code release .


I'm sorry if I caused you any trouble.


Best&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "serdarch/SERNet-Former"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 凌晨1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [serdarch/SERNet-Former] code release (Issue #3)





 
This repository is only being developed for additional language support and as a backup repository to the network
 with many basic and tutorial-based codes to emulate the development progress of the network.
 
I hope this answers your inquiry.
 Best
